# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='\u062e\u064a\u0627\u0631', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='question text', verbose_name='\u0646\u0635 \u0627\u0644\u0633\u0624\u0627\u0644')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.Question'),
        ),
    ]
