# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-13 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170411_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='next_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Question'),
        ),
    ]
