# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_choice_next_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='\u0639\u0646\u0648\u0627\u0646 \u0627\u0644\u0633\u0624\u0627\u0644', max_length=30),
        ),
    ]
